# Generated by Django 5.2.9 on 2025-12-05 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="任务名称")),
                ("dataset", models.CharField(max_length=255, verbose_name="数据集")),
                ("scene", models.CharField(max_length=255, verbose_name="场景")),
                (
                    "mode",
                    models.CharField(
                        choices=[("normal", "常规"), ("derain", "去雨")],
                        default="normal",
                        max_length=50,
                        verbose_name="模式",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("processing", "进行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="processing",
                        max_length=50,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "model_path",
                    models.CharField(
                        blank=True, max_length=1024, null=True, verbose_name="模型路径"
                    ),
                ),
            ],
            options={
                "verbose_name": "重建任务",
                "verbose_name_plural": "重建任务",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Annotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset", models.CharField(max_length=255)),
                ("scene", models.CharField(max_length=255)),
                ("image_name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("point", "点选"), ("box", "框选")], max_length=50
                    ),
                ),
                ("data", models.JSONField(verbose_name="标注数据")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        to="api.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "标注记录",
                "verbose_name_plural": "标注记录",
            },
        ),
    ]
